### ISSUE TITLE
Panic when paging skip greater than length of items slice

### ISSUE THREAD

**Issue by antonio-alexander** [pip-services3-go/pip-services3-data-go#6]
Good afternoon, 

A panic was pointed out to me when using memory persistence, and upon research I found that there wasn't appropriate bounds checking when attempting to get a subset of the items slice. I am able to consistently reproduce when the value for skip is greater than the length of the array.

Commandable recovers from the panic and prints the following message (semi-redacted):
`
[---:ERROR:2021-07-07T16:47:11Z] Failed to execute v1/xxx method: Execution xxx failed: runtime error: slice bounds out of range [10:0] Caused by: runtime error: slice bounds out of range [10:0]
`

https://github.com/pip-services3-go/pip-services3-data-go/blob/a96de237ed7c42d002be8852f4e84643be1c5ee1/persistence/MemoryPersistence.go#L242

**Comment by levichevdmitry** [comment]
Thanks for report! 
Error fixed. Please, use new version v1.1.5

**Comment by antonio-alexander** [comment]
Awesome, thanks @levichevdmitry
