### ISSUE TITLE
Unexpected panic when ID field is found but is already populated

### ISSUE THREAD

**Issue by antonio-alexander** [pip-services3-go/pip-services3-data-go#8]
https://github.com/pip-services3-go/pip-services3-data-go/blob/2f88468b38cb92a3f5f396123b904a966cc42597/persistence/Utilities.go#L218

I may be stretching the expected use case here, but wanted to bring up the issue and confirm (or resolve) the logic. This code:
```go
// GenerateObjectId is generates a new id value when it's empty
// Parameters:
//   - item *interface{}
//   an pointer on object to set id property
// Results saved in input object
func GenerateObjectId(item *interface{}) {
	value := *item
	idField := GetProperty(value, "Id")
	if idField != nil {
		if reflect.ValueOf(idField).IsZero() {
			SetObjectId(item, cdata.IdGenerator.NextLong())
		        return  //<-----------
		}
	}
	panic("'Id' or 'ID' field doesn't exist")
}
```
The code path will cause a panic if the id field is set (e.g. not generated by pip-services). I don't know if that's the intended function. This can be resolved by updating the code to return outside the reflect conditional rather than inside like so:
```go
// GenerateObjectId is generates a new id value when it's empty
// Parameters:
//   - item *interface{}
//   an pointer on object to set id property
// Results saved in input object
func GenerateObjectId(item *interface{}) {
	value := *item
	idField := GetProperty(value, "Id")
	if idField != nil {
		if reflect.ValueOf(idField).IsZero() {
			SetObjectId(item, cdata.IdGenerator.NextLong())
		}
		return  //<-----------
	}
	panic("'Id' or 'ID' field doesn't exist")
}
```
This should ensure that the panic ONLY occurs if there is no ID field. There's also a possibility that this could fail if the ID type is NOT long (maybe); I don't see anything off hand that tries to validate the data type before setting the value.

I can confirm that the code above does work if the value is NonZero. 

There may also be some bias in your tests in that they only contain the expected use cases rather than what the code allows (e.g. we're using strings for IDs and are generating them ourselves rather than allowing pip to do it for us).

**Comment by levichevdmitry** [comment]
Yes, of course. Already updated in new release https://github.com/pip-services3-go/pip-services3-data-go/releases/tag/v1.1.7

**Comment by antonio-alexander** [comment]
Huzzah! Thank you.
